app:
  name: MyApp
  version: 1.0.0

server:
  host: localhost
  port: 8080

database:
  engine: postgresql
  host: db.local
  port: 5432
  username: admin
  password: secret123

features:
  - login
  - signup
  - analytics
